### ISSUE TITLE
Package names in the visualization - district layout

### ISSUE THREAD

**Issue by stefanrinderle** [stefanrinderle/softvis3d#53]
It would be great to see the package name of the district in the visualization.

**Comment by cniweb** [comment]
Nice would be a popup at Mouse Over.

**Comment by stefanrinderle** [comment]
# Status

Added a first POC-like implementation to the new branch. We should use this to clarify, how we want to implement this feature and what needs to be done to finish it.

# Current impl examples

<img width="790" alt="grafik" src="https://cloud.githubusercontent.com/assets/2418659/23899515/b7f3b412-08b5-11e7-8e31-cfaa5dadaff1.png">

<img width="651" alt="grafik" src="https://cloud.githubusercontent.com/assets/2418659/23899523/bcc449de-08b5-11e7-915c-40999e7380e7.png">

# Todos

There are several things which needs to be improved.

## Code issues

- [ ] Font loading is async and just done anywhere. Should be done in sync on application start or object creation (see TODO in ObjectFactory.ts)
- [ ] It is important to know which kind of Layout is processed. This is currently done via a color check ;-) - should be changed to LayoutType check (see TODO in ObjectFactory.ts)
- [ ] The name is currently not available in the source SoftVis3dShape. Therefore, the name is resolved using the TreeService for each element. This is not only ugly, but also leaves us with a bad performance on big projects (see TODO in ObjectFactory.ts)
- [ ] The resulting SoftVis3dMesh object which is currently used needs an id. Do we need one? If yes, what to use?
- [ ] The "objects" should be implemented in a more OO manner
- [ ] Unit tests!

## Feature definition

- [ ] The text color is currently red. This should be adjusted to a "better" fitting color. Maybe we have to adjust the platform / street colors as well.
- [ ] If we introduce this, we definitely will need a config parameter for that because textures are really memory consuming. It will be needed to deactive this feature especially for bigger projects.
- [ ] The new config parameter should also be included in the direct link feature #3  

## Open questions

* How do you like it? I really do. 

Another way to do this would be a popup on mouse over, but i think this is more clear and helps to get an good overview.

* Overlappings / ...

Currently, the text can overlap a platform because the text is too big. This could be optimized but only solved 100 % if included in the layout algorithm (which i would want not to do). This can be very, very tricky and a huge layout algorithm would be needed.

I could live with overlappings and would try to optimize this without changing the layout.

**Comment by Ungolianth** [comment]
I would go for a sprite approach:
 * Something like in this [example](https://stemkoski.github.io/Three.js/Sprite-Text-Labels.html), but more subtle (and maybe sharper 😄)
 * Also don't show all at once, but decide on multiple factors (_distance to camera, package depth, package size_) to show or hide the labels
